<table id="ill-requests">
    <thead>
        <tr id="illview-header">
            <th>Author</th>
            <th>Title</th>
            <th>Patron name</th>
            <th>Patron barcode</th>
            <th>Biblio ID</th>
            <th>Library</th>
            <th>Status</th>
            <th>Additional status</th>
			<th class="placed">&nbsp;</th>
			<th class="placed_formatted">Date placed</th>
			<th class="updated">&nbsp;</th>
			<th class="updated_formatted">Updated on</th>
            <th>Request number</th>
            <th class="actions"></th>
        </tr>
    </thead>
    <tbody id="illview-body">
    </tbody>
</table>
